### ISSUE TITLE
Link to BLE API is not visible

### ISSUE THREAD

**Issue by andresag01** [ARMmbed/BLEIntros#8]
The link to the doxygen BLE API (https://docs.mbed.com/docs/ble-api/en/latest/api/) is not visible enough. I could only find one link in the [advanced developer site](https://docs.mbed.com/docs/ble-api/en/latest/api/index.html). Perhaps there should be another link in the [section overview](https://docs.mbed.com/docs/ble-intros/en/latest/Introduction/Overview/) or some other more visible place?

**Comment by iriark01** [comment]
There's actually a couple of links to it, but I'll add one to the front page.
